version: '3'

services: 
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - rabbitmq

    celery:
        build: .
        command: celery -A smsApi worker -l info
        volumes: 
            - .:/code
        depends_on:
            - rabbitmq

    # celery-beat:
    #     build: .
    #     command: celery -A smsApi beat -l info
    #     volumes: 
    #         - .:/code
    #     depends_on:
    #         - rabbitmq

    rabbitmq:
        image: rabbitmq:3.7