version: '3'

services: 
    web:
        build: .
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/code
        ports:
            - "8099:8000"
        depends_on:
            - rabbitmq
#             - migration
    
#     migration:
#         build: .
#         command: python manage.py migrate 
#         volumes:
#         - .:/code

    celery:
        build: .
        command: celery -A smsApi worker --beat --scheduler django --loglevel=info
        volumes: 
            - .:/code
        depends_on:
            - rabbitmq

#     migration:
#         build: .
#         command: python manage.py migrate

    # celery-beat:
    #     build: .
    #     command: $ celery -A [project-name] worker --beat --scheduler django --loglevel=info
    #     volumes: 
    #         - .:/code
    #     depends_on:
    #         - rabbitmq

    rabbitmq:
        image: rabbitmq:3.7

#celery -A smsApi beat -l info
#celery -A smsApi beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
